version: "3"

services: 
    admin:
        build:  
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
        command: npm start
        volumes: 
            - .:/app